language: python
python:
  - "2.7"
  - "3.6"

env:
  - PLATFORMIO_PROJECT_DIR=examples/arduino-blink
  - PLATFORMIO_PROJECT_DIR=examples/arduino-external-libs
  - PLATFORMIO_PROJECT_DIR=examples/arduino-internal-libs
  - PLATFORMIO_PROJECT_DIR=examples/native-blink

install:
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - platformio platform install file://.

script:
  - platformio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false

  slack:
    rooms:
      secure: l3gd68M7ZBaMPkXQiyG8yQdWlmGLQ5E75NgRpFY+zNpIZB2EbQFqYacGwt8KyICJ4IC3Z3Db78FqxpUpKiYD+AX74GwsLHKc7GlLsEzRaOByAtm/xFRut7Fh32OL6xEigz0LUaCDF/ZDXqPYZHhiX9/7jzyjHOhDUIuk9j924qFtT/CRa5FHh8zeXCVlO79YXCir/+pdhoQLW3majfm+MWnSFGFB4wbYrb0RzP6hs45uJWb1tFaw4xKe/qi65FEFgQ33R+A944xAiNfiKgEEKkFcGXn+0ljCTLpu+svd+COKXWOMD0f5GDj5pVni1s4i4uCZXznKacD3QSKLhLBypd5pebCAdq6s9SBXwpNUNZ7EvzCAOZ3maH2XbkckfSyh7fZZq4tnluOCmnu6gEdLSciemJCfv8Xe+TXgs05LlLg1q3gsqfZ/1kyILfADdVwprVpjwwgAsFF8VTuzV6WRw+gZm3giVIdlu7sLT+GPQ07vsS+3lsybQivm4ZjJuEIMuI8Gig7JcQwHbD1GD7Q5hoeBuEz5XEVxhc+0pUzMdKkajS9BP5ap1g6rylkesSNlAIpPnTQXx0Ejj7jAPBJE9UWJPZVRBuT4FYeJR5vYUSZ0dFv4WoS7dGMqelg9xj+Rbnb2TP3m0QkIEaUNz6nF/ARnJBsTW/6w+Iqc5otA1Yg=
    on_failure: always
    on_success: change
